### ISSUE TITLE
Forbidden (CSRF token missing or incorrect.): /add/

### ISSUE THREAD

**Issue by marcohald** [tjhorner/archivebox-exporter#17]
Hi,

I configured the Url as http://127.0.0.1:8000 and tried to add a Site and received 
```
Forbidden (CSRF token missing or incorrect.): /add/
"POST /add/ HTTP/1.1" 403 1019
```
I also tried to allow the Public Add with
```archivebox config --set PUBLIC_ADD_VIEW=true```
But the Error Message stays the same
Version:
```
archivebox version                          
/home/marco/archivebox/node_modules/yargs/node_modules/yargs-parser/build/index.cjs:1013
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/home/marco/archivebox/node_modules/yargs/node_modules/yargs-parser/build/index.cjs:1013:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/marco/archivebox/node_modules/yargs/build/index.cjs:1:58746)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
ArchiveBox v0.6.3
Cpython Linux Linux-5.15.0-10025-tuxedo-x86_64-with-glibc2.29 x86_64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.3          valid     /home/marco/.local/bin/archivebox                                           
 √  PYTHON_BINARY         v3.8.10         valid     /usr/bin/python3.8                                                          
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.8/dist-packages/django/bin/django-admin.py           
 √  CURL_BINARY           v7.68.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.20.3         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v16.14.0        valid     /run/user/1001/fnm_multishells/1732264_1653393754050/bin/node               
 √  SINGLEFILE_BINARY     v0.3.32         valid     ./node_modules/single-file/cli/single-file                                  
 √  READABILITY_BINARY    v0.0.4          valid     ./node_modules/readability-extractor/readability-extractor                  
 √  MERCURY_BINARY        v1.0.0          valid     ./node_modules/@postlight/mercury-parser/cli.js                             
 √  GIT_BINARY            v2.25.1         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2021.12.17     valid     /usr/local/bin/youtube-dl                                                   
 √  CHROME_BINARY         v101.0.4951.64  valid     /usr/bin/chromium                                                           
 √  RIPGREP_BINARY        v11.0.2         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /home/marco/.local/lib/python3.8/site-packages/archivebox                   
 √  TEMPLATES_DIR         3 files         valid     /home/marco/.local/lib/python3.8/site-packages/archivebox/templates         
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            6 files         valid     /home/marco/archivebox                                                      
 √  SOURCES_DIR           6 files         valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           4 files         valid     ./archive                                                                   
 √  CONFIG_FILE           150.0 Bytes     valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             236.0 KB        valid     ./index.sqlite3     
```
Edit:
The dev version as installed with 
npm install 'git+https://github.com/ArchiveBox/ArchiveBox.git#dev' --verbose

**Comment by Swedish-Hermit** [comment]
im trying out the extension at this moment i do not see a way of actually being able to use it i tried using the local 192**** ip with port same error also with the domain same thing i would prefer NOT to make the public being able too add sites

**Comment by tjhorner** [comment]
Sorry everyone, I'm particularly busy at the moment and won't get the chance to take a look at this in depth for a while.

It sounds like something changed on ArchiveBox's end so I'm not sure there's much I can do. PRs are welcome and I will do my best to review them promptly if someone finds a solution.

**Comment by pirate** [comment]
Closing this as stale, the documented process for linking the extension to the server is here: https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#browser-extension-usage

Please open a new issue if anyone still needs help!
